Namespace Entities

    ''' <summary>
    ''' Records the physical receipt of goods against a <see cref="PurchaseOrder"/>.
    ''' Multiple receipts may exist for one order (partial deliveries).
    ''' Receipt numbers follow the format GR-YYYY-XXXX (generated by the service layer).
    ''' </summary>
    Public Class GoodsReceipt
        Inherits MerchSys.SharedKernel.Entities.AuditableEntity

        ''' <summary>Foreign key to the <see cref="PurchaseOrder"/> this receipt is for.</summary>
        Public Property PurchaseOrderId As Integer

        ''' <summary>Sequential receipt number in GR-YYYY-XXXX format; assigned on creation.</summary>
        Public Property ReceiptNumber As String

        ''' <summary>UTC date and time when the goods were physically received at the store.</summary>
        Public Property ReceivedDate As DateTime

        ''' <summary>Username or name of the staff member who received the delivery.</summary>
        Public Property ReceivedBy As String

        ''' <summary>Free-text notes about this receipt, such as discrepancy observations; Nothing if not provided.</summary>
        Public Property Notes As String

        ' --- Navigation ---

        ''' <summary>The purchase order this goods receipt is recorded against.</summary>
        Public Property PurchaseOrder As PurchaseOrder

        ''' <summary>Individual product lines received in this delivery.</summary>
        Public Property Lines As ICollection(Of GoodsReceiptLine) = New List(Of GoodsReceiptLine)()

    End Class

End Namespace
