Imports MerchSys.SharedKernel.Enums

Namespace Entities

    ''' <summary>
    ''' Represents a purchase order issued to a vendor. Tracks the full lifecycle from
    ''' draft creation through goods receipt and closure. Order numbers follow the
    ''' format PO-YYYY-XXXX (generated by the service layer).
    ''' </summary>
    Public Class PurchaseOrder
        Inherits MerchSys.SharedKernel.Entities.SoftDeletableEntity

        ''' <summary>Sequential order number in PO-YYYY-XXXX format; assigned on creation.</summary>
        Public Property OrderNumber As String

        ''' <summary>Foreign key to the <see cref="Vendor"/> fulfilling this order.</summary>
        Public Property VendorId As Integer

        ''' <summary>Current lifecycle state of this purchase order.</summary>
        Public Property Status As PurchaseOrderStatus

        ''' <summary>UTC date and time when this purchase order was created.</summary>
        Public Property OrderDate As DateTime

        ''' <summary>Estimated UTC date the vendor expects to deliver; Nothing if not confirmed.</summary>
        Public Property ExpectedDeliveryDate As DateTime?

        ''' <summary>Sum of all line totals for this order.</summary>
        Public Property TotalAmount As Decimal

        ''' <summary>Free-text notes about this order; Nothing if not provided.</summary>
        Public Property Notes As String

        ' --- Navigation ---

        ''' <summary>The vendor supplying the goods on this order.</summary>
        Public Property Vendor As Vendor

        ''' <summary>Individual product lines that make up this order.</summary>
        Public Property Lines As ICollection(Of PurchaseOrderLine) = New List(Of PurchaseOrderLine)()

        ''' <summary>Goods receipts recorded against this purchase order.</summary>
        Public Property GoodsReceipts As ICollection(Of GoodsReceipt) = New List(Of GoodsReceipt)()

    End Class

End Namespace
