<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MerchSys.SharedKernel\MerchSys.SharedKernel.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.7" />
    <PackageReference Include="QuestPDF" Version="2026.5.0" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>MerchSys.Accounting</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Reports\Templates\Form2550M.template" />
    <EmbeddedResource Include="Reports\Templates\Form2550Q.template" />
    <EmbeddedResource Include="Reports\Templates\Form2551Q.template" />
  </ItemGroup>

</Project>
